//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAP.Foliacion.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cat_EstadoCancelados_Pagos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cat_EstadoCancelados_Pagos()
        {
            this.Tbl_SeguimientoHistoricoFormas_Pagos = new HashSet<Tbl_SeguimientoHistoricoFormas_Pagos>();
        }
    
        public int Id { get; set; }
        public string Estado { get; set; }
        public string Descrip { get; set; }
        public bool Activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_SeguimientoHistoricoFormas_Pagos> Tbl_SeguimientoHistoricoFormas_Pagos { get; set; }
    }
}
