//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAP.Foliacion.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cat_EstadosPago_Pagos
    {
        public Cat_EstadosPago_Pagos()
        {
            this.Tbl_Pagos = new HashSet<Tbl_Pagos>();
        }
    
        public int Id { get; set; }
        public string Descrip { get; set; }
        public string Activo { get; set; }
    
        public virtual ICollection<Tbl_Pagos> Tbl_Pagos { get; set; }
    }
}
