//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAP.Foliacion.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class cat_FiltroGrupoImpresionDelegaciones
    {
        public int Id { get; set; }
        public int GrupoImpresionDelegacion { get; set; }
        public string NombreComun { get; set; }
        public string DelegacionesIncluidas { get; set; }
    }
}
