//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAP.Foliacion.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class cat_FiltroConsultaDatosPersonalesNomina
    {
        public int Id { get; set; }
        public bool EsPena { get; set; }
        public Nullable<bool> EsPagomatico { get; set; }
        public Nullable<bool> Cheque { get; set; }
        public Nullable<int> Delegacion { get; set; }
        public string Consulta { get; set; }
    }
}
