//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAP.Foliacion.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class cat_ReportesCCancelados
    {
        public int Id { get; set; }
        public string Modulo { get; set; }
        public string TipoReporte { get; set; }
        public string NombreReporte { get; set; }
        public string Nomina { get; set; }
        public string Consulta { get; set; }
        public string Descrip { get; set; }
    }
}
