//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAP.Foliacion.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExepcionesCargaInterface
    {
        public int Id { get; set; }
        public string TipoExcepcion { get; set; }
        public int Id_nom { get; set; }
        public string Adicional { get; set; }
        public string Coment { get; set; }
        public string Problema { get; set; }
        public Nullable<int> diferenciasDeRegistros { get; set; }
        public int DiferenciaNoFoliados { get; set; }
        public int RegTotales { get; set; }
        public int RegFoliados { get; set; }
        public int Quincena { get; set; }
        public int AnioInterfas { get; set; }
    }
}
