//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAP.Foliacion.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOG_EXCEPCIONES
    {
        public int Id { get; set; }
        public string Clase { get; set; }
        public string Metodo { get; set; }
        public Nullable<int> Usuario { get; set; }
        public string Excepcion { get; set; }
        public string Comentario { get; set; }
        public System.DateTime Fecha { get; set; }
    }
}
