//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAP.Foliacion.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_InventarioContenedores
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_InventarioContenedores()
        {
            this.Tbl_InventarioDetalle = new HashSet<Tbl_InventarioDetalle>();
        }
    
        public int Id { get; set; }
        public int IdInventario { get; set; }
        public string NumOrden { get; set; }
        public int NumContenedor { get; set; }
        public string FolioInicial { get; set; }
        public string FolioFinal { get; set; }
        public int FormasTotalesContenedor { get; set; }
        public int FormasDisponiblesActuales { get; set; }
        public Nullable<int> FormasInhabilitadas { get; set; }
        public Nullable<int> FormasAsignadas { get; set; }
        public Nullable<int> FormasFoliadas { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public bool Activo { get; set; }
    
        public virtual Tbl_Inventario Tbl_Inventario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_InventarioDetalle> Tbl_InventarioDetalle { get; set; }
    }
}
