//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAP.Foliacion.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Inventario_Asignacion
    {
        public int Id { get; set; }
        public int IdAsignacion { get; set; }
        public int IdNombrePersona { get; set; }
        public int FoliosAsignados { get; set; }
        public string FolioInicial { get; set; }
        public string FolioFinal { get; set; }
        public System.DateTime FechaAsignacion { get; set; }
        public bool Activo { get; set; }
    
        public virtual Tbl_Inventario_AsignacionPersonal Tbl_Inventario_AsignacionPersonal { get; set; }
        public virtual Tbl_Inventario_Detalle Tbl_Inventario_Detalle { get; set; }
    }
}
