//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAP.Foliacion.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_SeguimientoHistoricoFormas_Pagos
    {
        public int Id { get; set; }
        public int IdTbl_Pagos { get; set; }
        public System.DateTime FechaCambio { get; set; }
        public int ChequeAnterior { get; set; }
        public Nullable<int> ChequeNuevo { get; set; }
        public string MotivoRefoliacion { get; set; }
        public string RefoliadoPor { get; set; }
        public bool EsCancelado { get; set; }
        public string ReferenciaCancelado { get; set; }
        public Nullable<int> IdCat_EstadoCancelado { get; set; }
        public bool Activo { get; set; }
    
        public virtual Cat_EstadoCancelados_Pagos Cat_EstadoCancelados_Pagos { get; set; }
    }
}
