//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAP.Foliacion.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Referencias_Cancelaciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Referencias_Cancelaciones()
        {
            this.Tbl_Pagos = new HashSet<Tbl_Pagos>();
        }
    
        public int Id { get; set; }
        public int Anio { get; set; }
        public string Numero_Referencia { get; set; }
        public System.DateTime Fecha_Creacion { get; set; }
        public string Creado_Por { get; set; }
        public int FormasPagoDentroReferencia { get; set; }
        public bool EsCancelado { get; set; }
        public string FolioDocumento { get; set; }
        public byte[] ArchivoSustento { get; set; }
        public bool Activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Pagos> Tbl_Pagos { get; set; }
    }
}
