//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAP.Foliacion.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Inventario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Inventario()
        {
            this.Tbl_CuentasBancarias = new HashSet<Tbl_CuentasBancarias>();
            this.Tbl_InventarioContenedores = new HashSet<Tbl_InventarioContenedores>();
        }
    
        public int Id { get; set; }
        public int FormasDisponibles { get; set; }
        public string UltimoFolioInventario { get; set; }
        public string UltimoFolioUtilizado { get; set; }
        public Nullable<decimal> EstimadoMeses { get; set; }
        public bool Activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_CuentasBancarias> Tbl_CuentasBancarias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_InventarioContenedores> Tbl_InventarioContenedores { get; set; }
    }
}
