//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAP.Foliacion.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Inventario_Detalle
    {
        public Tbl_Inventario_Detalle()
        {
            this.Tbl_Inventario_Asignacion = new HashSet<Tbl_Inventario_Asignacion>();
            this.Tbl_Inventario_Inhabilitados = new HashSet<Tbl_Inventario_Inhabilitados>();
        }
    
        public int Id { get; set; }
        public int IdInventario { get; set; }
        public string NumOrden { get; set; }
        public int NumContenedor { get; set; }
        public string FolioInicial { get; set; }
        public string FolioFinal { get; set; }
        public int TotalFormasContenedor { get; set; }
        public int FormasDisponiblesActuales { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public bool Activo { get; set; }
    
        public virtual Tbl_Inventario Tbl_Inventario { get; set; }
        public virtual ICollection<Tbl_Inventario_Asignacion> Tbl_Inventario_Asignacion { get; set; }
        public virtual ICollection<Tbl_Inventario_Inhabilitados> Tbl_Inventario_Inhabilitados { get; set; }
    }
}
