//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAP.Foliacion.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_CuentasBancarias
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_CuentasBancarias()
        {
            this.Tbl_Pagos = new HashSet<Tbl_Pagos>();
            this.Tbl_Solicitudes = new HashSet<Tbl_Solicitudes>();
        }
    
        public int Id { get; set; }
        public string NombreBanco { get; set; }
        public string Abreviatura { get; set; }
        public string Cuenta { get; set; }
        public int IdCuentaBancaria_TipoPagoCuenta { get; set; }
        public Nullable<int> IdInventario { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaBaja { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<bool> InicioBaja { get; set; }
        public Nullable<int> IdctabancaIPD { get; set; }
        public Nullable<int> IdBancoIPD { get; set; }
    
        public virtual Tbl_CuentaBancarias_TipoPagoCuenta Tbl_CuentaBancarias_TipoPagoCuenta { get; set; }
        public virtual Tbl_Inventario Tbl_Inventario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Pagos> Tbl_Pagos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Solicitudes> Tbl_Solicitudes { get; set; }
    }
}
