//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAP.Foliacion.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_InventarioDetalle
    {
        public Tbl_InventarioDetalle()
        {
            this.Tbl_inventarioAsignacion = new HashSet<Tbl_inventarioAsignacion>();
            this.Tbl_InventarioInhabilitado = new HashSet<Tbl_InventarioInhabilitado>();
        }
    
        public int Id { get; set; }
        public int IdContenedor { get; set; }
        public string NumFolio { get; set; }
        public Nullable<int> IdIncidencia { get; set; }
    
        public virtual ICollection<Tbl_inventarioAsignacion> Tbl_inventarioAsignacion { get; set; }
        public virtual Tbl_InventarioContenedores Tbl_InventarioContenedores { get; set; }
        public virtual Tbl_InventarioTipoIncidencia Tbl_InventarioTipoIncidencia { get; set; }
        public virtual ICollection<Tbl_InventarioInhabilitado> Tbl_InventarioInhabilitado { get; set; }
    }
}
